name: Merge upstream branches
on:
  schedule:
    - cron:  '* * * * *'
  workflow_dispatch: {}
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name 'LIFE-Home'
          git config --global user.email 'mklifehome@gmail.com'

          git pull --unshallow

          git remote add upstream https://github.com/lifehome-illinois/MistyGPT.git
          git fetch upstream

          git checkout main
          git merge --no-edit upstream/main
          git push origin main
